### ISSUE TITLE
3D动物姿态估计的论文

### ISSUE THREAD

**Issue by sunbin1357** [anl13/animal_papers#1]
是否看到过3D animal pose estimation 的相关论文或代码？

**Comment by anl13** [comment]
抱歉之前没看到这个issue。有的哈，看是什么样的论文。做3D mesh的主要看一下Angjoo kanazawa的论文，其他做姿态的不是很多，我的列表里都有

**Comment by sunbin1357** [comment]
你好，我没看到列表里专门做姿态估计的😂。能具体说一下是哪一个吗

**Comment by anl13** [comment]
比如做2D pose的DeepLabCut，DeepPosekit，AniPose， DeepGraphPose, SLEAP,  Cross-Domain Adaptation for Animal Pose Estimation, Learning from synthetic animals, 
做3D 的有AniPose，Lions and Tigers,  Three-D Safari, MONET, OpenMonkeyStudio, Creatures great and SMAL, 3D Menagerie, RGBD-dog

我现在的整理还比较混乱，没有专门归类，抱歉。后期我会增加一些类别上的安排
