### ISSUE TITLE
你好，我最近又发现了两篇相关文章，不知是否可以整合一下

### ISSUE THREAD

**Issue by YNCris** [anl13/animal_papers#2]
一篇Neuron：Continuous Whole-Body 3D Kinematic Recordings across the Rodent Behavioral Repertoire
一篇arxiv：Muti-view Mouse Social Behaviour Recognition with Deep Graphic Model

**Comment by YNCris** [comment]
再补充一篇biorxiv：SLEAP: multi-animal pose tracking

**Comment by anl13** [comment]
抱歉之前没看到这个issue，我会添加进去的哈

**Comment by anl13** [comment]
已经添加了，非常感谢！
